import { UIForm } from 'mithril-ui-form-plugin';

export const assessmentModel = [
  {
    id: 'desc',
    label: 'Description',
    placeholder: 'Describe the capability in detail.',
    type: 'textarea',
    className: 'col s12',
  },
  {
    id: 'capabilityPartners',
    label: 'Partners',
    pageSize: 5,
    repeat: true,
    type: [
      {
        id: 'partnerId',
        label: 'Partner',
        type: 'select',
        options: 'partners',
        className: 'col s4 m2',
      },
      {
        id: 'goal',
        label: 'Goals',
        placeholder: 'Specify long and short term goals',
        type: 'textarea',
        className: 'col s8 m10',
      },
    ],
    className: 'col m12',
  },
  {
    id: 'documentation',
    label: 'Documentation',
    repeat: true,
    pageSize: 5,
    type: [
      {
        id: 'documentId',
        label: 'Document ID',
        type: 'text',
        className: 'col s3 m2',
      },
      {
        id: 'label',
        label: 'Title',
        type: 'text',
        className: 'col s6 m6',
      },
      {
        id: 'link',
        label: 'URL',
        type: 'url',
        className: 'col s3 m4',
      },
    ],
    className: 'col m12',
  },
  {
    id: 'taskAssessment',
    type: 'assessment',
    options: 'mainTasks',
    optionLabel: 'Main goals',
    assessmentOptions: 'taskScale',
    assessmentLabel: 'Importance',
    descriptionLabel: 'Explanation',
    overallAssessmentLabel: 'Maximum importance',
    overallAssessment: 'max',
  },
  {
    id: 'performanceAssessment',
    type: 'assessment',
    options: 'performanceAspects',
    optionLabel: 'Performance aspect',
    assessmentOptions: 'performanceScale',
    assessmentLabel: 'Performance',
    descriptionLabel: 'Explanation',
    overallAssessmentLabel: 'Average performance',
    overallAssessment: 'avg',
  },
  {
    id: 'gapAssessment',
    type: 'assessment',
    options: 'mainGaps',
    optionLabel: 'Problem areas',
    assessmentOptions: 'gapScale',
    assessmentLabel: 'Problem',
    descriptionLabel: 'Explanation',
    overallAssessmentLabel: 'Problem cause is well known',
    overallAssessment: 'max',
  },
  {
    id: 'assessmentId',
    label: 'Overall assessment',
    type: 'lookup-table',
    table: 'assessmentTable',
    options: 'assessmentScale',
    rowId: 'taskAssessment.assessmentId',
    colId: 'performanceAssessment.assessmentId',
  },
  { type: 'md', value: '###### GO / NO GO decision<br>', className: 'right-align' },
  {
    id: 'shouldDevelop',
    type: 'switch',
    className: 'right-align',
    label: '',
    options: [
      { id: 'NO GO', label: 'NO GO' },
      { id: 'go', label: 'GO' },
    ],
  },
] as UIForm;
