import { UIForm } from 'mithril-ui-form-plugin';

export const developmentModel = [
  {
    id: 'projectProposals',
    label: 'Projects and project proposals',
    repeat: true,
    pageSize: 1,
    filterLabel: 'label',
    type: [
      { id: 'id', autogenerate: 'timestamp' },
      {
        id: 'label',
        label: 'Proposal name',
        show: '!approved',
        type: 'text',
        className: 'col s6 m4',
      },
      {
        id: 'label',
        label: 'Project name',
        show: 'approved',
        type: 'text',
        className: 'col s6 m4',
      },
      {
        id: 'start',
        label: 'Start time',
        placeholder: 'YYYY Q1 or YYYY M1',
        type: 'text',
        className: 'col s3 m4',
      },
      {
        id: 'duration',
        label: 'Duration',
        placeholder: 'In months',
        type: 'text',
        className: 'col s3 m4',
      },
      {
        id: 'proposal',
        label: 'Project summary',
        type: 'textarea',
        className: 'col s12',
      },
      {
        id: 'projectPartners',
        label: 'Partners',
        pageSize: 5,
        repeat: true,
        type: [
          {
            id: 'partnerId',
            label: 'Partner',
            type: 'select',
            options: 'partners',
            className: 'col s4 m2',
          },
          {
            id: 'persons',
            label: 'Persons involved',
            type: 'textarea',
            className: 'col s8 m10',
          },
        ],
        className: 'col m12',
      },
      {
        id: 'gapAssessment',
        type: 'assessment',
        options: 'mainGaps',
        optionLabel: 'Problem areas',
        assessmentOptions: 'gapScale',
        assessmentLabel: 'Addressed',
        descriptionLabel: 'How is it addressed?',
      },
      {
        id: 'performanceAssessment',
        type: 'assessment',
        options: 'performanceAspects',
        optionLabel: 'Performance aspect',
        assessmentOptions: 'performanceScale',
        assessmentLabel: 'Performance',
        descriptionLabel: 'Explanation',
        overallAssessmentLabel: 'Expected performance',
        overallAssessment: 'avg',
      },
      { type: 'md', value: '###### PROJECT APPROVED<br>', className: 'margins right-align' },
      {
        id: 'approved',
        type: 'switch',
        className: 'margins right-align',
        label: '',
        options: [
          { id: 'no', label: 'NO' },
          { id: 'yes', label: 'YES' },
        ],
      },
    ],
  },
] as UIForm;
