import { UIForm } from 'mithril-ui-form';

export const settingsModel = [
  { id: 'partner-settings', type: 'section', label: 'Partners' },
  { type: 'md', value: '##### Partner/stakeholder settings' },
  {
    id: 'stakeholderTypes',
    label: 'Stakeholder types',
    repeat: true,
    pageSize: 1,
    propertyFilter: 'label',
    sortProperty: 'id',
    type: [
      { id: 'id', type: 'text', className: 'col s4 m3' },
      { id: 'label', type: 'text', label: 'Name', className: 'col s8 m9' },
    ],
  },
  {
    id: 'partners',
    label: 'Partner organisations',
    repeat: true,
    pageSize: 1,
    propertyFilter: 'label',
    type: [
      { id: 'id', autogenerate: 'id' },
      {
        id: 'label',
        label: 'Organisation / department',
        type: 'text',
        className: 'col s12 m8',
      },
      {
        id: 'type',
        label: 'Type of stakeholder',
        type: 'select',
        options: 'stakeholderTypes',
        className: 'col s12 m4',
      },
    ],
  },
  { id: 'category-settings', type: 'section', label: 'Categories' },
  { type: 'md', value: '##### Category settings' },
  {
    id: 'categories',
    label: 'Categories for capabilities',
    repeat: true,
    pageSize: 1,
    propertyFilter: 'label',
    sortProperty: 'id',
    type: [
      { id: 'id', type: 'text', className: 'col s4 m3' },
      { id: 'label', type: 'text', label: 'Name', className: 'col s8 m9' },
      { id: 'desc', type: 'textarea', label: 'Description', className: 'col s12' },
      {
        id: 'subcategories',
        label: 'Subcategories',
        repeat: true,
        pageSize: 1,
        propertyFilter: 'label',
        sortProperty: 'id',
        tabindex: 2,
        className: 'col offset-s2 s10',
        type: [
          { id: 'id', type: 'text', className: 'col s4 m3' },
          { id: 'label', type: 'text', label: 'Name', className: 'col s8 m9' },
          { id: 'desc', type: 'textarea', label: 'Description', className: 'col s12' },
        ],
      },
    ],
  },
  { id: 'task-settings', type: 'section', label: 'Tasks' },
  { type: 'md', value: '##### Task settings' },
  {
    id: 'mainTasks',
    label: 'Main tasks a capability needs to support',
    repeat: true,
    pageSize: 1,
    sortProperty: 'id',
    type: [
      { id: 'id', label: 'ID', type: 'text', className: 'col s3 m2' },
      { id: 'label', label: 'Task', type: 'text', className: 'col s9 m10' },
      { id: 'desc', label: 'Description', type: 'textarea', className: 'col s12' },
    ],
  },
  {
    id: 'taskScale',
    label: 'Scale for the main tasks',
    repeat: true,
    pageSize: 1,
    sortProperty: 'id',
    type: [
      { id: 'id', label: 'ID', type: 'text', className: 'col s3 m2' },
      { id: 'label', label: 'Value', type: 'text', className: 'col s9 m10' },
    ],
  },
  { id: 'performance-settings', type: 'section', label: 'Performance' },
  { type: 'md', value: '##### Performance settings' },
  {
    id: 'performanceAspects',
    label: 'Performance aspects',
    repeat: true,
    pageSize: 1,
    sortProperty: 'id',
    type: [
      { id: 'id', label: 'ID', type: 'text', className: 'col s3 m2' },
      { id: 'label', label: 'Task', type: 'text', className: 'col s9 m10' },
      { id: 'desc', label: 'Description', type: 'textarea', className: 'col s12' },
    ],
  },
  {
    id: 'performanceScale',
    label: 'Scale for performance score',
    repeat: true,
    pageSize: 1,
    sortProperty: 'id',
    type: [
      { id: 'id', label: 'ID', type: 'text', className: 'col s3 m2' },
      { id: 'label', label: 'Value', type: 'text', className: 'col s9 m10' },
    ],
  },
  { id: 'gap-settings', type: 'section', label: 'Gaps' },
  { type: 'md', value: '##### Gaps settings' },
  {
    id: 'mainGaps',
    label: 'Common gaps or causes of problems',
    repeat: true,
    pageSize: 1,
    sortProperty: 'id',
    type: [
      { id: 'id', label: 'ID', type: 'text', className: 'col s3 m2' },
      { id: 'label', label: 'Gap', type: 'text', className: 'col s9 m10' },
      { id: 'desc', label: 'Description', type: 'textarea', className: 'col s12' },
    ],
  },
  {
    id: 'gapScale',
    label: 'Scale for the gap',
    repeat: true,
    pageSize: 1,
    sortProperty: 'id',
    type: [
      { id: 'id', label: 'ID', type: 'text', className: 'col s3 m2' },
      { id: 'label', label: 'Value', type: 'text', className: 'col s9 m10' },
    ],
  },
  { id: 'assessment-settings', type: 'section', label: 'Assessment' },
  { type: 'md', value: '##### Task to performance table lookup' },
  {
    id: 'assessmentScale',
    label: 'Scale for assessment score',
    repeat: true,
    pageSize: 1,
    sortProperty: 'id',
    type: [
      { id: 'id', label: 'ID', type: 'text', className: 'col s3 m2' },
      { id: 'label', label: 'Value', type: 'text', className: 'col s9 m10' },
    ],
  },
  {
    id: 'assessmentTable',
    type: 'create-lookup-table',
    label: 'task \\ perf. scale',
    options: 'assessmentScale',
    rows: 'taskScale',
    cols: 'performanceScale',
  },
] as UIForm;
