export type Answer = string | number | boolean | undefined;

export type Answers = {
  timestamp: number;
  saved: boolean;
  Q01_crafting?: number;
  Q01_life_events_zin?: number;
  Q01_taakeisen?: number;
  Q01_zin_betekenis?: number;
  Q02_crafting?: number;
  Q02_crafting_behoefte?: number;
  Q02_life_events_leefstijl?: number;
  Q02_taakeisen_uitdaging?: number;
  Q03_crafting?: number;
  Q03_crafting_behoefte?: number;
  Q03_org_midd_craften?: number;
  Q03_taakeisen_obstakel?: number;
  Q04_crafting?: number;
  Q04_crafting_behoefte?: number;
  Q04_energiegevers_loskomen?: number;
  Q04_werkhulpbronnen?: number;
  Q05_crafting?: number;
  Q05_energiegevers_herstellen?: number;
  Q05_positieve_ervaringen_werk?: number;
  Q05_psycap?: number;
  Q06_Effectieve_zelfsturing?: number;
  Q06_leider_hulpbronnen?: number;
  Q06_psycap?: number;
  Q06_zelfondermijnend_gedrag?: number;
  Q07_Effectieve_zelfsturing?: number;
  Q07_inspanning_capaciteit?: number;
  Q07_leider_taakeisen?: number;
  Q07_psycap?: number;
  Q08_Extra_inspanning?: number;
  Q08_inspanning_geleverd?: number;
  Q08_leider_veiligklimaat?: number;
  Q08_psycap?: number;
  Q09_Extra_inspanning?: number;
  Q09_gezklachten?: number;
  Q10_Extra_inspanning?: number;
  Q10_leefstijl?: number;
  Q11_bevlogenheid?: number;
  Q12_bevlogenheid?: number;
  Q13_bevlogenheid?: number;
  Q14_Psych_loskomen_werk?: number;
  Q15_Psych_loskomen_werk?: number;
  Q16_belang_taakeisen_halen?: number;
  Q17_belang_taakeisen_halen?: number;
  Q18_basic_needs?: number;
  Q19_basic_needs?: number;
  Q20_basic_needs?: number;
  Q21_burnout?: number;
  Q22_burnout?: number;
  Q23_veilig_psychsoc_klimaat?: number;
  [key: string]: Answer;
};
